name: deploy github packages (docker)

on: 
  push:
    branches:
      - ghpackages-test

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build the Docker image
        run: docker build . -t docker.pkg.github.com/area363/ninechronicles.standalone/ninechronicles-headless:git-${{ github.sha }} -t docker.pkg.github.com/area363/ninechronicles.standalone/ninechronicles-headless:latest --build-arg COMMIT=git-${{ github.sha }}
      - name: login
        run: echo '${{ secrets.GH_ACCESS_TOKEN  }}' | docker login https://docker.pkg.github.com -u '${{ secrets.GH_USERNAME }}' --password-stdin
      - name: push git version
        run: docker push docker.pkg.github.com/area363/ninechronicles.standalone/ninechronicles-headless:git-${{ github.sha }}
      - name: push latest version
        run: docker push docker.pkg.github.com/area363/ninechronicles.standalone/ninechronicles-headless:latest
